import { LLMProvider, LLMGenerationSettings, LLMResponse } from "./index";

export class MockLLMProvider implements LLMProvider {
  name = "MockLLM";

  async generate<T>(
    promptVersion: string,
    prompt: string,
    schema: any,
    settings?: LLMGenerationSettings
  ): Promise<LLMResponse<T>> {
    // In a real mock, you'd match the prompt/schema to return something reasonable.
    // For V1, we'll return a stubbed response.
    const stubData: any = {
      confidence: 95,
      reasoning: "Generated by MockLLM",
      warnings: [],
      seoTitle: "Mocked SEO Title",
      seoDescription: "Mocked SEO Description",
      keywords: ["mock", "test"]
    };

    return {
      data: stubData as T,
      model: "mock-model-v1",
      settings: settings || { temperature: 0.7 },
      promptVersion
    };
  }
}

// Global instance for the intelligence layer to use
export const llmProvider = new MockLLMProvider();
