import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-surface": "#191c1e",
                "on-background": "#191c1e",
                "on-secondary-fixed": "#002113",
                "on-primary-container": "#dfdbff",
                "surface-variant": "#e0e3e5",
                "on-surface-variant": "#474554",
                "secondary-fixed": "#6ffbbe",
                "tertiary-container": "#5a6278",
                "primary-fixed-dim": "#c5c0ff",
                "inverse-primary": "#c5c0ff",
                "on-secondary-fixed-variant": "#005236",
                "outline": "#787585",
                "surface-tint": "#564bcb",
                "surface-container-low": "#f2f4f6",
                "tertiary-fixed": "#dae2fd",
                "on-tertiary-container": "#d7def9",
                "surface-container-lowest": "#ffffff",
                "surface-container-highest": "#e0e3e5",
                "surface-dim": "#d8dadc",
                "inverse-surface": "#2d3133",
                "surface-container": "#eceef0",
                "success-green": "#10B981",
                "inverse-on-surface": "#eff1f3",
                "brand-indigo": "#5A4FCF",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "surface-bright": "#f7f9fb",
                "on-primary": "#ffffff",
                "on-tertiary-fixed": "#131b2e",
                "on-primary-fixed-variant": "#3d2fb2",
                "tertiary": "#424a60",
                "secondary-container": "#6cf8bb",
                "outline-variant": "#c8c4d6",
                "primary": "#4134b6",
                "on-tertiary-fixed-variant": "#3f465c",
                "surface": "#f7f9fb",
                "secondary": "#006c49",
                "on-secondary": "#ffffff",
                "on-error-container": "#93000a",
                "surface-container-high": "#e6e8ea",
                "surface-white": "#FFFFFF",
                "primary-container": "#5a4fcf",
                "background": "#f7f9fb",
                "tertiary-fixed-dim": "#bec6e0",
                "secondary-fixed-dim": "#4edea3",
                "text-main": "#0F172A",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "on-secondary-container": "#00714d",
                "on-primary-fixed": "#130067",
                "primary-fixed": "#e3dfff"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "stack-sm": "12px",
                "stack-md": "24px",
                "margin-mobile": "16px",
                "margin-desktop": "40px",
                "base": "8px",
                "stack-lg": "48px",
                "gutter": "24px",
                "container-max": "1200px",
                // Fallbacks for standard Tailwind spacing (needed by existing components)
                4: "0.25rem",
                8: "0.5rem",
                12: "0.75rem",
                16: "1rem",
                24: "1.5rem",
                32: "2rem",
                48: "3rem",
                64: "4rem",
                96: "6rem",
            },
            fontFamily: {
                sans: ["var(--font-outfit)", "system-ui", "sans-serif"],
                "display-lg": ["var(--font-outfit)"],
                "headline-lg": ["var(--font-outfit)"],
                "headline-lg-mobile": ["var(--font-outfit)"],
                "title-md": ["var(--font-outfit)"],
                "body-md": ["var(--font-outfit)"],
                "body-lg": ["var(--font-outfit)"],
                "label-md": ["var(--font-outfit)"],
                "label-sm": ["var(--font-outfit)"]
            },
            fontSize: {
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
export default config;
