import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["var(--font-outfit)", "system-ui", "sans-serif"],
                "headline-lg": ["var(--font-outfit)"],
                "display-lg": ["var(--font-outfit)"],
                "metric-xl": ["var(--font-outfit)"],
                "body-sm": ["var(--font-plus-jakarta-sans)"],
                "label-bold": ["var(--font-plus-jakarta-sans)"],
                "body-md": ["var(--font-plus-jakarta-sans)"],
                "body-lg": ["var(--font-plus-jakarta-sans)"],
                "headline-md": ["var(--font-outfit)"],
                "headline-lg-mobile": ["var(--font-outfit)"]
            },
            fontSize: {
                "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "metric-xl": ["40px", {"lineHeight": "1.0", "fontWeight": "800"}],
                "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "label-bold": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}]
            },
            spacing: {
                "container-max": "1200px",
                "card-padding": "1.25rem",
                "gutter": "1.5rem",
                "stack-md": "1rem",
                "section-gap": "4rem",
                "stack-sm": "0.5rem"
            },
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
                "tertiary-fixed-dim": "#ffb599",
                "surface-bright": "#f9f9ff",
                "inverse-surface": "#293040",
                "surface-white": "#FFFFFF",
                "on-tertiary-container": "#ffe0d5",
                "tertiary-container": "#b54000",
                "on-secondary-fixed-variant": "#005236",
                "outline": "#7b7487",
                "on-primary-fixed": "#25005a",
                "surface-tint": "#732ee4",
                "on-primary-container": "#ede0ff",
                "on-tertiary-fixed-variant": "#7f2b00",
                "surface-dim": "#d3daef",
                "on-tertiary": "#ffffff",
                "primary": "#630ed4",
                "tertiary": "#8d3000",
                "on-background": "#141b2b",
                "primary-fixed": "#eaddff",
                "secondary-container": "#6cf8bb",
                "primary-fixed-dim": "#d2bbff",
                "on-surface": "#141b2b",
                "tertiary-fixed": "#ffdbce",
                "on-secondary": "#ffffff",
                "surface": "#f9f9ff",
                "secondary-fixed": "#6ffbbe",
                "surface-variant": "#dce2f7",
                "on-surface-variant": "#4a4455",
                "surface-container-highest": "#dce2f7",
                "outline-variant": "#ccc3d8",
                "on-primary-fixed-variant": "#5a00c6",
                "urgency-orange": "#EA580C",
                "error-container": "#ffdad6",
                "surface-container-lowest": "#ffffff",
                "error": "#ba1a1a",
                "secondary": "#006c49",
                "on-primary": "#ffffff",
                "primary-container": "#7c3aed",
                "on-error": "#ffffff",
                "on-secondary-fixed": "#002113",
                "secondary-fixed-dim": "#4edea3",
                "on-tertiary-fixed": "#370e00",
                "surface-container": "#e9edff",
                "inverse-primary": "#d2bbff",
                "background-soft": "#F9FAFB",
                "inverse-on-surface": "#edf0ff",
                "verified-green": "#10B981",
                "surface-container-high": "#e1e8fd",
                "on-error-container": "#93000a",
                "surface-container-low": "#f1f3ff",
                "on-secondary-container": "#00714d"
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
export default config;
